[package]
name = "notox"
version = "0.1.0"
authors = ["n4n5"]
edition = "2021"
description = "no toxic names anymore"
license = "MIT"
homepage = "https://github.com/Its-Just-Nans/notox"
repository = "https://github.com/Its-Just-Nans/notox"
license-file = "LICENSE"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
