name: Spell Check
on:
    push:
        branches: ["main"]

    workflow_dispatch:

jobs:
    run:
        name: Spell Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Actions Repository
              uses: actions/checkout@v4

            - name: Check spelling of entire workspace
              uses: crate-ci/typos@master
